In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [23]:
from sklearn.ensemble import RandomForestClassifier

In [24]:
X = [[0, 0], [1, 1]]
y = [0, 1]

rfc = RandomForestClassifier()

In [25]:
rfc.fit(X,y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [26]:
X_test = [[0, 0], [1, 1]]
y_test = [0, 1]

In [27]:
y_pred = rfc.predict(X_test)

In [28]:
y_pred

array([0, 1])

In [29]:
from sklearn.metrics import classification_report, confusion_matrix

In [30]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00         1
          1       1.00      1.00      1.00         1

avg / total       1.00      1.00      1.00         2

[[1 0]
 [0 1]]


In [8]:
X1 = [[0, 0], [1, 1],[1, 0], [1, 0], [1, 0], [0, 0], [1, 1],[1, 0], [1, 0], [1, 0], [0, 0], [1, 1],[1, 0], [1, 0], [1, 0], [0, 0], [1, 1],[1, 0], [1, 0], [1, 0]]
y1 = [0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1]

In [17]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X1, y1, test_size=0.33, random_state=0)

In [11]:
X_test

[[1, 0], [1, 1], [1, 0], [1, 0], [0, 0], [1, 0], [1, 1]]

In [12]:
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [13]:
y_pred = rfc.predict(X_test)

In [14]:
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

             precision    recall  f1-score   support

          0       1.00      0.33      0.50         3
          1       0.67      1.00      0.80         4

avg / total       0.81      0.71      0.67         7

[[1 2]
 [0 4]]


In [15]:
from sklearn import tree
import graphviz
dot_data = tree.export_graphviz(rfc, out_file=None)
graph = graphviz.Source(dot_data)
graph.render("tree_graph")

ModuleNotFoundError: No module named 'graphviz'